version: '3.4'

services:
  web:
    environment:
      - CONTRAST__SERVER__NAME=RailsGoat-container-prod
      - CONTRAST__SERVER__ENVIRONMENT=Production
      - CONTRAST__ASSESS__ENABLE=false
      - CONTRAST__PROTECT__ENABLE=true
